### ISSUE TITLE
İçeriğin içerisindeki görselleri indirmiyor

### ISSUE THREAD

**Issue by harunalp29** [saltun/sBotClass#10]
Selamlar, öncelikle sınıfınızı çok beğeniyorum. Ancak yakın zamanda yaşadığım sorun içerikteki görselleri indirmemesi. Yani videoda veya dokümanda indirip kendi yolunu veriyor. Hem linux sunucuda hem localde denedim ve localde olmamasını başta normal karşıladım. Yüksek oranda bir data çekimi yapacağım ve şimdilik wordpress son sürümü kullanmaktayım. (Şu anki sürüm: 5.7.2) Acaba sınıfınızda bir güncelleme mi yapmanız gerekiyor yoksa sürümle alakalı bir sorun mu var anlamış değilim.

` $sBot->title=$title; 
	$sBot->content=$sBot->new_content($content);
	$sBot->status="draft";
	$sBot->time=date("Y-m-d H:i:s");
	$sBot->author=1;
	$sBot->cat=1;
	$sBot->thumbnail = $sBot->download_image($img);
	echo $sBot->addPost(true,false);`

bu şekilde test datamı çekip ekliyorum oldukça güzel geliyor. Ancak görselleri indirmediği için son aşamaya henüz geçemedim.

**Comment by saltun** [comment]
Merhaba,
Tekrar sınıfı güncelleyip deneme şansınız var mı ? olmazsa indirmeye çalıştığınız görsellerin url adresini gönderir misiniz  ?

**Comment by harunalp29** [comment]
Öncelikle kısa sürede dönüşünüz için teşekkürler , şu anda her şey yolunda görünüyor. Zaten sizin görsellerinizi indirerek denemiştim, şuan sağlıklı şekilde çalışıyor. Emeğinize sağlık.

**Comment by harunalp29** [comment]
Tekrardan merhabalar ,sınıf içerisinde seflink fonksiyonu ile görselin adını kaydettiriyorsunuz ve burada %(yüzde) ifadesi replace ettirilmemiş. Daha çok bu tarz başlık ve içerikler çektiğim için sorun baş gösterdi. % ifadesini boşlukla değiştirerek fonksiyonu güncelledim ve sorunsuz çalışıyor. Siz de vaktiniz olduğunda sınıfta o güncellemeyi atarsanız yeni kullanıcılarınız bu konuda sorun yaşamaz. Tekrardan teşekkürler.
