### ISSUE TITLE
new_content Fonksiyon Problemi 

### ISSUE THREAD

**Issue by ZgrK** [saltun/sBotClass#3]
Merhaba,

Örnekte verdiğiniz gibi new_content fonksiyonunu kullanmaya çalışıyorum fakat aşağıdaki hata ile karşılaşıyorum.

<img width="424" alt="screen shot 2016-07-04 at 8 55 58 pm" src="https://cloud.githubusercontent.com/assets/879674/16567653/bdc748e8-4229-11e6-8595-be20a8e53438.png">

İçerik olarakta açıklamada yazdığınız gibi deniyorum fakat böyle bir sorun yaşıyorum.

**Comment by saltun** [comment]
Tam olarak nasıl kullanıyorsunuz acaba ? fonksiyona içerik gönderdiğinize emin misiniz ?

**Comment by ZgrK** [comment]
```
$icerik='
<a href="http://savascanaltun.com.tr/wp-content/themes/sca2/images/logo.png"><img src="http://savascanaltun.com.tr/wp-content/themes/sca2/images/logo.png"  /></a>
<a href="http://savascanaltun.com.tr/timthumb.php?src=http://savascanaltun.com.tr/wp-content/uploads/2014/08/php-framework.jpg&w=178&h=141&zc=1"><img src="http://savascanaltun.com.tr/timthumb.php?src=http://savascanaltun.com.tr/wp-content/uploads/2014/08/php-framework.jpg&w=178&h=141&zc=1"></a>
';
echo $sBot->new_content($icerik);
```

Direk bu şekilde deniyorum yine yapmıyor

**Comment by saltun** [comment]
wp-content/uploads/images dizinin de yazma izni olduğuna emin misiniz ?

**Comment by ZgrK** [comment]
Evet eminim bu fonksiyonu kullanmadan herşey çok düzgün çalışıyor $sBot->download_image kullanarak karşı taraftan indirebiliyorum görseli.
<img width="386" alt="screen shot 2016-07-04 at 10 01 26 pm" src="https://cloud.githubusercontent.com/assets/879674/16568445/e3fff0e2-4232-11e6-85c2-7aa9d09ac7e8.png">

Yukarda ki görselde de gördüğünüz gibi görseller oluşuyor.

**Comment by saltun** [comment]
Sınıfa bir güncelleme getirdim şuan ki hali ile dener misiniz ?

**Comment by ZgrK** [comment]
Aynı hata devam ediyor malesef :(
