### ISSUE TITLE
Eklenen Konu ID'sini Çekme

### ISSUE THREAD

**Issue by veyakup** [saltun/sBotClass#7]
Merhabalar, öncelikle sınıf gerçekten uzun süredir ağır işlerimi kolaylıkla hallediyor ihtiyacım olan herşey içerisinde var teşekkürler. Bir sorum olacaktı, eklediğim bir konunun id sini yada linkini ekledikten sonra ekrana nasıl yazdırabilirim?

**Comment by saltun** [comment]
Merhaba,
addPost() fonksiyonunu geri dönen değer olarak içeriğin benzersiz numarasını geri çevirmektedir. 
Örnek : 
`$post_id=$sBot->addPost();`
